---
title: "Pollutant Exposure Data"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(sp)
library(geosphere)
library(openxlsx)
library(xts)

`%!in%` <- Negate(`%in%`)
```

```{r}
census <- read.xlsx("CensusList.xlsx")
CBSA_census_list <- unique(census$CBSA.Title)

city_list <- c("New York","Los Angeles","Chicago","Dallas","Houston","Washington-Arlington",
               "Miami-Fort","Philadelphia-Camden","Atlanta","Phoenix","Boston","San Francisco",
               "Riverside-San","Detroit","Seattle","Minneapolis","San Diego",
               "Tampa","Denver","St. Louis","Baltimore","Charlotte-Concord","Orlando",
               "San Antonio","Portland-Vancouver")

ind_collection <- c()
for (city_name in city_list){
  ind <- which(lapply(CBSA_census_list, function(x) grep(city_name, x)) == 1)
  ind_collection <- c(ind_collection, ind)
}

census <- dplyr::select(filter(census,CBSA.Title %in% CBSA_census_list[ind_collection]),"County/County.Equivalent","State.Name")

countystate <- paste(census[,1],census[,2])
```

```{r}

pm_2016 <- read.csv("Datasets/daily_88101_2016.csv")
pm_2017 <- read.csv("Datasets/daily_88101_2017.csv")
pm_2018 <- read.csv("Datasets/daily_88101_2018.csv")
pm_2019 <- read.csv("Datasets/daily_88101_2019.csv")

pm_2016_2 <- read.csv("Datasets/daily_88502_2016.csv")
pm_2017_2 <- read.csv("Datasets/daily_88502_2017.csv")
pm_2018_2 <- read.csv("Datasets/daily_88502_2018.csv")
pm_2019_2 <- read.csv("Datasets/daily_88502_2019.csv")

pm_combined <- rbind(pm_2016,pm_2017,pm_2018,pm_2019)
pm2_combined <- rbind(pm_2016_2,pm_2017_2,pm_2018_2,pm_2019_2)

CleanCombinedData <- function(pm_combined){
  
  pm_combined_clean <- pm_combined %>% filter(Observation.Percent >= 50) 
  
  CBSA_list <- unique(pm_combined_clean$CBSA.Name)
  CBSA_ind <- c(19,29,39,47,49,62,77,79,82,86,89,96,114,116,174,179,192,196,227,248,281,316,319,321,342)
  
  CBSA_list[CBSA_ind]
  
  pm_combined_clean <- mutate(pm_combined_clean, combined_county_state = paste(County.Name, State.Name))
  
  pm_combined_clean <- pm_combined_clean %>% filter((combined_county_state %in% countystate) | CBSA.Name %in% CBSA_list[CBSA_ind])
  
  pm_combined_clean <- subset(pm_combined_clean, Arithmetic.Mean >= 0 )
  
  unique(pm_combined_clean$combined_county_state)[unique(pm_combined_clean$combined_county_state) %!in% countystate]
  
  lon_list_ap <- unique(pm_combined_clean$Longitude)
  lat_list_ap <- unique(pm_combined_clean$Latitude)
  samdur_list <- unique(pm_combined_clean$Sample.Duration)
  
  pm_combined.df <- data.frame()
  date_list <- seq.Date(as.Date("2016-01-01"),as.Date("2019-12-31"),"day")
  
  for (lat_ind in 1:length(lat_list_ap)){
    working_pm_combined <- filter(pm_combined_clean,Latitude == lat_list_ap[lat_ind])
    
    method1 <- filter(working_pm_combined,Sample.Duration == samdur_list[1])
    method1 <- dplyr::select(method1,Date.Local, Arithmetic.Mean)
    if (dim(method1)[1]>0){method1 <- aggregate(Arithmetic.Mean ~ Date.Local, method1, mean)}
    method1 <- as.data.frame(method1) %>% 
      mutate(Date = as.Date(Date.Local)) %>%
      complete(Date = date_list)
    
    method2 <- filter(working_pm_combined,Sample.Duration == samdur_list[2])
    method2 <- dplyr::select(method2,Date.Local, Arithmetic.Mean)
    if (dim(method2)[1]>0){method2 <- aggregate(Arithmetic.Mean ~ Date.Local, method2, mean)}
    method2 <- as.data.frame(method2) %>% 
      mutate(Date = as.Date(Date.Local)) %>%
      complete(Date = date_list)
    
    method3 <- filter(working_pm_combined,Sample.Duration == samdur_list[3])
    # if (length(unique(method3$POC)) > 1){
      # print(lat_ind)
    # }
    method3 <- dplyr::select(method3,Date.Local, Arithmetic.Mean)
    if (dim(method3)[1]>0){method3 <- aggregate(Arithmetic.Mean ~ Date.Local, method3, mean)}
    method3 <- as.data.frame(method3) %>% 
      mutate(Date = as.Date(Date.Local)) %>%
      complete(Date = date_list)
    
    
    missing_inds <- which(is.na(method3$Arithmetic.Mean))
    method3$Arithmetic.Mean[missing_inds] <- method2$Arithmetic.Mean[missing_inds]
  
    missing_inds <- which(is.na(method3$Arithmetic.Mean))
    method3$Arithmetic.Mean[missing_inds] <- method1$Arithmetic.Mean[missing_inds]
    
    
    to_add.df <- data.frame(Latitude = lat_list_ap[lat_ind],
                            Longitude = lon_list_ap[lat_ind],
                            Date = method3$Date,
                            armean = method3$Arithmetic.Mean)
    
    pm_combined.df <- rbind(pm_combined.df,to_add.df)
  }
  return(pm_combined.df)
}

pm_combined.df <- CleanCombinedData(pm_combined)
pm2_combined.df <- CleanCombinedData(pm2_combined)


# for (i in 1:length(date_list)){
#   print(sum(pm_combined.df$Date == date_list[i]))
# }
# 
# x <- pm_combined.df
# for (i in 2:length(pm_combined.df$Date)){
#   if (pm_combined.df$Date[i-1] == pm_combined.df$Date[i]){
#     print(pm_combined.df$Latitude[i])
#     y <- pm_combined.df$Latitude[i]
#     print(pm_combined.df$Date[i])
#     break
#   }
# }
# 
# 
# which(pm_combined.df$Latitude == y)

lon_list_ap <- unique(pm_combined.df$Longitude)
lat_list_ap <- unique(pm_combined.df$Latitude)

lon_list2_ap <- unique(pm2_combined.df$Longitude)
lat_list2_ap <- unique(pm2_combined.df$Latitude)

```


```{r}
lon_list_ap <- unique(pm_combined.df$Longitude)
lat_list_ap <- unique(pm_combined.df$Latitude)


la_lon <- -118.239390
la_lat <- 33.950949

det_lon <- -83.0458
det_lat <- 42.3314

distHaversine(c(la_lon,la_lat),c(det_lon,det_lat), r=6378137) * 0.001

GetMonitorPM <- function(lon_list_ap,lat_list_ap,lon,lat, return_mult, radius){
  combined_lonlat <- cbind(lon_list_ap,lat_list_ap)
  dist <- apply(combined_lonlat,1,distHaversine,p1 = c(lon,lat)) * .001
  if (min(dist) > radius){
    # print("Error: No measurements within radius")
    return(NA)
  }
  if (return_mult){
    within_rad <- which(dist<radius)
    return(cbind(lon_list_ap[within_rad],lat_list_ap[within_rad]))
  } else {
   return(cbind(lon_list_ap[which.min(dist)],lat_list_ap[which.min(dist)]))
  }
}

GetMonitorPM(lon_list_ap,lat_list_ap,la_lon,la_lat,F,8)
which.min(abs(lon_list_ap-la_lon) + (abs(lat_list_ap-la_lat)))

GetAP <- function(pm_data, lon_list_ap, lat_list_ap, lon, lat, return_mult, radius){

  lonlat <- GetMonitorPM(lon_list_ap,lat_list_ap, lon,lat,return_mult,radius)
  
  if (is.na(lonlat[1])){
    return(NA)
  }
  
  ap_df <- data.frame()
  
  for (i in 1:dim(lonlat)[1]){
    lon_adj <- lonlat[i,1]
    lat_adj <- lonlat[i,2]
    
    dist <- distHaversine(c(lon,lat),c(lon_adj,lat_adj), r=6378137) * 0.001
    ap_series <- filter(pm_data, Latitude == lat_adj & Longitude == lon_adj)
    
    to_add <- dplyr::select(ap_series,armean, Date)
    to_add$AirMonDist <- dist
    
    ap_df <- rbind(ap_df, to_add)
  }
  
  return(ap_df)
}


la_ap <- GetAP(pm_combined.df, lon_list_ap, lat_list_ap, la_lon, la_lat,F,10)
det_ap <- GetAP(pm_combined.df, lon_list_ap, lat_list_ap, det_lon, det_lat,F,10)

ggplot() +
  geom_point(data=la_ap, aes(x=as.Date(Date), y=armean, color="LA ")) + 
  geom_point(data=det_ap, aes(x=as.Date(Date), y=armean, color="Detroit")) + 
  scale_x_date(date_breaks = "3 month", date_labels =  "%b") +
  theme(axis.text.x=element_text(angle=60, hjust=1)) +
  labs(x = "Month", y = "Arithmetic Mean PM2.5 (µg/m³)", title = "Arithmetic Mean PM2.5 (µg/m³) in 2016")

```

```{r}

MultiAM.df <- GetAP(pm_combined.df, lon_list_ap, lat_list_ap, la_lon, la_lat,T,11)

ggplot() +
  geom_point(data=MultiAM.df, aes(x=as.Date(Date), y=armean, color=factor(round(AirMonDist,2)))) + 
  scale_x_date(date_breaks = "3 month", date_labels =  "%b") +
  theme(axis.text.x=element_text(angle=60, hjust=1)) +
  labs(x = "Month", y = "Arithmetic Mean PM2.5 (µg/m³)", title = "Arithmetic Mean PM2.5 (µg/m³) in LA 2016",color = "Distance")

plot(filter(MultiAM.df,AirMonDist < 7)$armean - filter(MultiAM.df,AirMonDist > 7)$armean,
     xlab = "Day",
     ylab = "Difference Between Monitors",
     main = "Air Monitor Residuals")


InverseWeightedAvg <- function(MultiAM.df){
  spread_ap <- spread(MultiAM.df,AirMonDist,armean)
  dist_vec <- as.double(colnames(spread_ap)[2:dim(spread_ap)[2]])
  inv_weighted_vec <- numeric(dim(spread_ap)[1])
  for(i in 1:dim(spread_ap)[1]){
    
    armeans <- spread_ap[i,2:dim(spread_ap)[2]]
    
    if (sum(is.na(armeans)) == 3){
      inv_weighted_vec[i] <- NA
    } else {
      total_dist <- as.integer(!is.na(armeans)) %*% (1/dist_vec)
      armeans * (1/dist_vec)
      inv_weighted_armean <- sum((armeans / dist_vec)/total_dist, na.rm = T)
      
      inv_weighted_vec[i] <- inv_weighted_armean
    }
  }
  inv_weighted.df <- mutate(dplyr::select(spread_ap,Date),armean = inv_weighted_vec)
  
  missing_days <- which(inv_weighted.df$armean == 0)
  inv_weighted.df$armean[missing_days] <- NA
  
  return(inv_weighted.df)
}

inv_weighted.df <- InverseWeightedAvg(MultiAM.df)
  
ggplot() +
  geom_point(data=inv_weighted.df, aes(x=as.Date(Date), y=armean), shape = 0) +  
  geom_point(data=MultiAM.df, aes(x=as.Date(Date), y=armean, color=factor(round(AirMonDist,3)))) + 
  scale_x_date(date_breaks = "3 month", date_labels =  "%b") +
  theme(axis.text.x=element_text(angle=60, hjust=1)) +
  labs(x = "Month", y = "Arithmetic Mean PM2.5 (µg/m³)", title = "Arithmetic Mean PM2.5 (µg/m³) in LA", color = "Distance")

ggplot() +
  geom_point(data=inv_weighted.df, aes(x=as.Date(Date), y=armean), shape = 0) +  
  geom_point(data=MultiAM.df, aes(x=as.Date(Date), y=armean, color=factor(round(AirMonDist,3)))) + 
  scale_x_date(date_breaks = "1 month", date_labels =  "%b",
               limits = as.Date(c('2018-06-01','2018-09-01'))) +
  theme(axis.text.x=element_text(angle=60, hjust=1)) +
  labs(x = "Month", y = "Arithmetic Mean PM2.5 (µg/m³)", title = "Arithmetic Mean PM2.5 (µg/m³) in LA Summer 2018", color = "Distance")

```

```{r}

MultiAM.df <- GetAP(pm_combined.df, lon_list_ap, lat_list_ap, det_lon, det_lat,T,5.5)

ggplot() +
  geom_point(data=MultiAM.df, aes(x=as.Date(Date), y=armean, color=factor(round(AirMonDist,2)))) + 
  scale_x_date(date_breaks = "3 month", date_labels =  "%b") +
  theme(axis.text.x=element_text(angle=60, hjust=1)) +
  labs(x = "Month", y = "Arithmetic Mean PM2.5 (µg/m³)", title = "Arithmetic Mean PM2.5 (µg/m³) in Detroit 2016",color = "Distance")

plot(filter(MultiAM.df,AirMonDist < 5)$armean - filter(MultiAM.df,AirMonDist > 5)$armean,
     xlab = "Day",
     ylab = "Difference Between Monitors",
     main = "Air Monitor Residuals")


InverseWeightedAvg <- function(MultiAM.df){
  spread_ap <- spread(MultiAM.df,AirMonDist,armean)
  dist_vec <- as.double(colnames(spread_ap)[2:dim(spread_ap)[2]])
  inv_weighted_vec <- numeric(dim(spread_ap)[1])
  for(i in 1:dim(spread_ap)[1]){
    
    armeans <- spread_ap[i,2:dim(spread_ap)[2]]
    
    if (sum(is.na(armeans)) == 3){
      inv_weighted_vec[i] <- NA
    } else {
      total_dist <- as.integer(!is.na(armeans)) %*% (1/dist_vec)
      armeans * (1/dist_vec)
      inv_weighted_armean <- sum((armeans / dist_vec)/total_dist, na.rm = T)
      
      inv_weighted_vec[i] <- inv_weighted_armean
    }
  }
  inv_weighted.df <- mutate(dplyr::select(spread_ap,Date),armean = inv_weighted_vec)
  
  missing_days <- which(inv_weighted.df$armean == 0)
  inv_weighted.df$armean[missing_days] <- NA
  
  return(inv_weighted.df)
}

inv_weighted.df <- InverseWeightedAvg(MultiAM.df)
  
ggplot() +
  geom_point(data=inv_weighted.df, aes(x=as.Date(Date), y=armean), shape = 0) +  
  geom_point(data=MultiAM.df, aes(x=as.Date(Date), y=armean, color=factor(round(AirMonDist,3)))) + 
  scale_x_date(date_breaks = "3 month", date_labels =  "%b") +
  theme(axis.text.x=element_text(angle=60, hjust=1)) +
  labs(x = "Month", y = "Arithmetic Mean PM2.5 (µg/m³)", title = "Arithmetic Mean PM2.5 (µg/m³) in Detroit 2016", color = "Distance")

ggplot() +
  geom_point(data=inv_weighted.df, aes(x=as.Date(Date), y=armean), shape = 0) +  
  geom_point(data=MultiAM.df, aes(x=as.Date(Date), y=armean, color=factor(round(AirMonDist,3)))) + 
  scale_x_date(date_breaks = "1 month", date_labels =  "%b",
               limits = as.Date(c('2018-12-01','2019-01-01'))) +
  theme(axis.text.x=element_text(angle=60, hjust=1)) +
  labs(x = "Month", y = "Arithmetic Mean PM2.5 (µg/m³)", title = "Arithmetic Mean PM2.5 (µg/m³) in Detroit December 2018", color = "Distance")

```

```{r}
library(ncdf4) # package for netcdf manipulation
library(raster) # package for raster manipulation
library(rgdal) # package for geospatial analysis
library(ggplot2) # package for plotting
library(weathermetrics) #rhum to dew


temp_data <- nc_open("tmmx_2016.nc")
# {
#     sink('tmmx_2016.txt')
#  print(nc_data)
#     sink()
# }

hum_data <- nc_open("../../netcdf files/rmin_2019.nc")
{
    sink('rmin_2019.txt')
 print(hum_data)
    sink()
}

lon_list_temp <- ncvar_get(temp_data, "lon")
lat_list_temp <- ncvar_get(temp_data, "lat", verbose = F)
t_list <- ncvar_get(temp_data, "day")

# lon_hum <- ncvar_get(hum_data, "lon")
# lat_hum <- ncvar_get(hum_data, "lat")
# t_hum <- ncvar_get(hum_data, "day")
# 
# sum(lon_hum != lon_list_temp)
# sum(lat_hum != lat_list_temp)
# sum(t_hum != t_list)

temp_array <- ncvar_get(temp_data, "air_temperature")
hum_array <- ncvar_get(hum_data, "relative_humidity")

fillvalue_temp <- ncatt_get(temp_data, "air_temperature", "_FillValue")
nc_close(temp_data) 
temp_array[temp_array == fillvalue_temp$value] <- NA

fillvalue_hum <- ncatt_get(hum_data, "relative_humidity", "_FillValue")
nc_close(hum_data) 
hum_array[hum_array == fillvalue_hum$value] <- NA

temp_array <- convert_temperature(temp_array,old_metric = "k", new_metric = "c")
dew_array <-  humidity.to.dewpoint(hum_array,temp_array,temperature.metric = "celsius")

at_array <- -2.653 + (.994 * temp_array) + (.0153 * dew_array^2)

day <- 1

# temp_slice <- temp_array[,,day]
# hum_slice <- hum_array[,,day]
# dew_slice <- dew_array[,,day]
at_slice <- at_array[,,day]


# r <- raster(t(temp_slice), xmn=min(lon_temp), xmx=max(lon_temp), ymn=min(lat_temp), ymx=max(lat_temp), crs=CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs+ towgs84=0,0,0"))
# plot(r)
# 
# r <- raster(t(hum_slice), xmn=min(lon_temp), xmx=max(lon_temp), ymn=min(lat_temp), ymx=max(lat_temp), crs=CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs+ towgs84=0,0,0"))
# plot(r)
# 
# r <- raster(t(dew_slice), xmn=min(lon_temp), xmx=max(lon_temp), ymn=min(lat_temp), ymx=max(lat_temp), crs=CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs+ towgs84=0,0,0"))
# plot(r)

day <- as.Date("2016-01-01") + day - 1

r <- raster(t(at_slice), xmn=min(lon_list_temp), xmx=max(lon_list_temp), ymn=min(lat_list_temp), ymx=max(lat_list_temp), crs=CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs+ towgs84=0,0,0"))
# plot(r, 
#      main = paste0("Apparent Temp on ",format(day, format="%B %d %Y")),
#      xlab = "Longitude",
#      ylab = "Latitude")



rm(temp_array)
rm(dew_array)
rm(hum_array)
gc()
r_brick <- brick(at_array, xmn=min(lat_list_temp), xmx=max(lat_list_temp), ymn=min(lon_list_temp), ymx=max(lon_list_temp), crs=CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs+ towgs84=0,0,0"))

# r_brick <- flip(t(r_brick), direction='y')
r_brick <- t(r_brick)

GrabAT <- function(r_brick, lon_list_temp, lat_list_temp, lon, lat){
  
  lon_adj <- lon_list_temp[which(abs(lon_list_temp-lon)==min(abs(lon_list_temp-lon)))]
  lat_adj <- lat_list_temp[which(abs(lat_list_temp-lat)==min(abs(lat_list_temp-lat)))]
  
  at_series <- extract(r_brick, SpatialPoints(cbind(lon_adj,lat_adj)), method='simple')
  
  at_temp_df <- data.frame(day = seq(as.Date("2016-01-01"),as.Date("2016-12-31"), by = "day"),
                           temp = c(at_series))
  
  return(at_temp_df)
}

```

```{r}
library(sf)
library(sp)
library(tmap)
library(spdep)
library(tigris)
library(dplyr)
library(tidyverse)
library(tidycensus)

set.seed(10)

metros <-  get_acs(
  geography = "cbsa",
  variables = "DP03_0021P",
  summary_var = "B01003_001",
  survey = "acs1",
  year = 2019
) %>%
  slice_max(summary_est, n = 20)

mn_tracts <- map_dfr(c("MD"), ~{
  tracts(.x, cb = TRUE, year = 2020)
}) %>%
  st_transform(8528)

mn_metro <- core_based_statistical_areas(cb = TRUE, year = 2020) %>%
  filter(str_detect(NAME, "Baltimore")) %>%
  st_transform(8528)

mn_tracts_within <- mn_tracts %>%
  st_filter(mn_metro, .predicate = st_within)

random_points <- st_sample(mn_metro, size = 100)

ggplot() + 
  geom_sf(data = mn_tracts_within, fill = "white", color = "grey") + 
  geom_sf(data = mn_metro, fill = NA, color = "red") + 
  geom_sf(data = random_points, color = "blue") + 
  theme_void()


random_points_latlon <- st_transform(random_points, "+proj=longlat +datum=WGS84")
rcoord <- st_coordinates(random_points_latlon)

sim.df <- data.frame()
for (i in 1:dim(rcoord)[1]){
  
  to_add <- GetAP(pm_combined.df, lon_list_ap, lat_list_ap, rcoord[i,1], rcoord[i,2],T,15)
  if (!is.na(to_add[[1]][1])){
    to_add <- InverseWeightedAvg(to_add)
    to_add$lat <- rcoord[i,2]
    to_add$lon <- rcoord[i,1]
    to_add$person <- i
    sim.df <- rbind(sim.df,to_add)
  }
}

person_list <- unique(sim.df$person)
rdates <- sample(seq(as.Date('2016/01/11'), as.Date('2016/12/31'), by="day"), length(person_list))

ggplot() + 
  geom_sf(data = mn_tracts_within, fill = "white", color = "grey") + 
  geom_sf(data = mn_metro, fill = NA, color = "red") + 
  geom_sf(data = random_points[person_list], color = "blue") + 
  theme_void()

environmental_exp <- data.frame()
for (i in 1:length(rdates)){
  working_sim.df <- filter(sim.df, person == person_list[i])
  death_date <- rdates[i]
  lag_dates <- seq(death_date-10,death_date, by = "day")
  pollution_exposure <-filter(working_sim.df, Date %in% lag_dates)
  
  temp_exposure <- GrabAT(r_brick, lon_list_temp, lat_list_temp,pollution_exposure$lon[1],pollution_exposure$lat[1])
  temp_exposure <- filter(temp_exposure, day %in% lag_dates)
  
  environmental_exp_working <- dplyr::select(pollution_exposure,Date,armean, person)
  environmental_exp_working$temp <- temp_exposure$temp
  
  environmental_exp <- rbind (environmental_exp,environmental_exp_working)
}

```




```{r}
library(gridExtra)

PrintIndividual <- function(individual, environmental_exp,person_list){


  environmental_exp_filt <- filter(environmental_exp, person == person_list[individual])
  
  p <- ggplot() +
    geom_line(data=environmental_exp_filt, aes(x=Date, y=temp)) +
    # scale_x_date(date_breaks = "d", date_labels =  "%d") +
    # theme(axis.text.x=element_text(angle=60, hjust=1)) +
    labs(x = "Month", y = "Apparent Temp (C)", title = "Daily AT Highs in 2016")
  
  
  g <- ggplot() +
    geom_point(data=environmental_exp_filt, aes(x=Date, y=armean)) + 
    # theme(axis.text.x=element_text(angle=60, hjust=1)) +
    labs(x = "Month", y = "Arithmetic Mean PM2.5 (µg/m³)", title = "Arithmetic Mean PM2.5 (µg/m³) in 2016")
  
  m <- ggplot() + 
    geom_sf(data = mn_tracts_within, fill = "white", color = "grey") + 
    geom_sf(data = mn_metro, fill = NA, color = "red") + 
    geom_sf(data = random_points[person_list], color = "blue") + 
    geom_sf(data = random_points[person_list[individual]], color = "forestgreen", size = 3) + 
    theme_void()
  
  return(grid.arrange(p,m,g,ncol = 2))
  
}


PrintIndividual(1,environmental_exp,person_list)
PrintIndividual(10,environmental_exp,person_list)
PrintIndividual(20,environmental_exp,person_list)

```

```{r}
num_of_points <- 100
city_coverage <- numeric(length(city_list))

for (city_ind in 1:length(city_list)){
  metro <- core_based_statistical_areas(cb = TRUE, year = 2020) %>%
    filter(str_detect(NAME, city_list[city_ind])) %>%
    st_transform(8528)
  
  random_points <- st_sample(metro, size = num_of_points)
  random_points_latlon <- st_transform(random_points, "+proj=longlat +datum=WGS84")
  rcoord <- st_coordinates(random_points_latlon)
  rs <- 0
  
  for (i in 1:dim(rcoord)[1]){
    to_add <- GetAP(pm_combined.df, lon_list_ap, lat_list_ap, rcoord[i,1], rcoord[i,2],F,15)
    if (!is.na(to_add[[1]][1])){
      rs <- rs + 1
    }
  }
  
  city_coverage[city_ind] <- (rs/num_of_points) * 100
}
  
city_coverage.df <- data.frame(Coverage = city_coverage,
                               City = city_list)
ggplot() + 
  geom_point(data = city_coverage.df, aes(x = City, y = Coverage)) + 
  theme(axis.text.x=element_text(angle=60, hjust=1)) + 
  labs(x = "City", y = "Percent Air Monitor Coverage", title = "Air Monitor Coverage by City") 
```